version: "3"

services:

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_pgsql
    environment:
      - "POSTGRES_PASSWORD=openbamz"
      - "POSTGRESQL_MAX_CONNECTIONS=1000"
    volumes:
      - dev-open-bamz-pg:/bitnami/postgresql
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U postgres -d postgres"
      timeout: 2s

  # container used by code editor plugin to provide ssh access
  bamz-ssh:
    build:
      context: .
      dockerfile: Dockerfile_ssh # FIXME publish image from plugin
    hostname: bamz-ssh
    ports:
      - "2222:22"
    volumes:
      - dev-open-bamz-data:/users:rw
      - ./ssh_keys/id_rsa.pub:/root/.ssh/authorized_keys # SSH private key for code editor plugin, create your own !
    restart: always
  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "NODE_ENV=development"
      - "JWT_PRIVATE_KEY_FILE=/home/node/jwtRS256.key"
      - "JWT_PUBLIC_KEY_FILE=/home/node/jwtRS256.key.pub"
      - "DB_HOST=db"
      - "DB_USER=postgres"
      - "DB_PASSWORD=openbamz"
      - "DB_PORT=5432"
      - "DB_NAME=_openbamz"
      - "DATA_DIR=/home/node/data"
      - "PLUGINS_DIR=/home/node/plugins"
      - "SSH_PORT=22" # SSH options for code editor plugin
      - "SSH_CONTAINER_HOST=bamz-ssh" # SSH options for code editor plugin
      - "SSH_ADMIN_USER=root" # SSH options for code editor plugin
      - "SSH_ADMIN_PRIVATE_KEY_FILE=/home/node/.ssh-bamz_id_rsa" # SSH options for code editor plugin
      - "BINARY_STORAGE_PATH=/home/node/binary" # options for binary storage plugin (if you want storage on disk)
    volumes:
      - dev-open-bamz-data:/home/node/data
      - ~/open-bamz-plugins:/home/node/plugins
      - ./jwt_keys/jwtRS256.key:/home/node/jwtRS256.key:ro 
      - ./jwt_keys/jwtRS256.key.pub:/home/node/jwtRS256.key.pub:ro 
      - ./ssh_keys/id_rsa:/home/node/.ssh-bamz_id_rsa:ro # SSH private key for code editor plugin, create your own !
      - dev-open-bamz-binary:/home/node/binary # volume for binary storage plugin (if you want storage on disk)
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openbamz.rule=HostRegexp(`{host:[A-Za-z0-9-_]*.{0,1}test3.bakino.fr}`)"
      - "traefik.http.routers.openbamz.priority=5"
      - "traefik.http.services.openbamz.loadbalancer.server.port=3000"
      - "traefik.http.routers.openbamz.entrypoints=websecure"
      - "traefik.http.routers.openbamz.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.openbamz.tls.domains[0].main=test3.bakino.fr"
      - "traefik.http.routers.openbamz.tls.domains[0].sans=*.test3.bakino.fr"

    depends_on: 
      db: 
        condition: service_healthy

volumes:
  dev-open-bamz-pg:
    external: true
  dev-open-bamz-data:
    external: true
  dev-open-bamz-binary:
    external: true

networks:
  default:
    external:
      name: traefik
